I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 285, in script
    e "We're pleased that you've taken the opportunity to join the fast-growing field of human identification software."
TypeError: Missing required positional arguments: 'text'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 285, in script
    e "We're pleased that you've taken the opportunity to join the fast-growing field of human identification software."
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/character.py", line 1003, in do_display
    display_say(who,
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/core.py", line 4055, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/screen.py", line 476, in visit_all
    callback(self)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/core.py", line 4055, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/screen.py", line 487, in per_interact
    self.update()
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/display/screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ast.py", line 296, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ast.py", line 232, in apply
    raise TypeError(
TypeError: Missing required positional arguments: 'text'

Linux-6.2.0-39-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.1.3.23091805
DataVille 1.0
Mon Dec 18 14:56:07 2023
