I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 289, in script
    call screen image_gui(task, "Done!")
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/screens.rpy", line 1691, in execute
    screen image_gui(state, button_text):
  File "game/screens.rpy", line 1691, in execute
    screen image_gui(state, button_text):
  File "game/screens.rpy", line 1696, in execute
    python:
  File "game/screens.rpy", line 1697, in <module>
    from pathlib import Path
ImportError: cannot import name 'Path' from 'pathlib' (python-packages/pathlib.py)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 289, in script
    call screen image_gui(task, "Done!")
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/exports.py", line 3336, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/core.py", line 3499, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/core.py", line 3969, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/screen.py", line 476, in visit_all
    callback(self)
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/core.py", line 3969, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/screen.py", line 487, in per_interact
    self.update()
  File "/home/brent/dataville-renpy/renpy-8.1.0-sdk/renpy/display/screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 1691, in execute
    screen image_gui(state, button_text):
  File "game/screens.rpy", line 1691, in execute
    screen image_gui(state, button_text):
  File "game/screens.rpy", line 1696, in execute
    python:
  File "game/screens.rpy", line 1697, in <module>
    from pathlib import Path
ImportError: cannot import name 'Path' from 'pathlib' (python-packages/pathlib.py)

Linux-6.2.0-33-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.1.0.23051307
DataVille 1.0
Wed Oct  4 18:19:15 2023
